//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomTools.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomTools.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string TrayMenu_Options {
            get {
                return ResourceManager.GetString("TrayMenu_Options", resourceCulture);
            }
        }

        internal static string TrayMenu_Exit {
            get {
                return ResourceManager.GetString("TrayMenu_Exit", resourceCulture);
            }
        }

        internal static string Options_Title {
            get {
                return ResourceManager.GetString("Options_Title", resourceCulture);
            }
        }

        internal static string Options_StartWithWindows {
            get {
                return ResourceManager.GetString("Options_StartWithWindows", resourceCulture);
            }
        }

        internal static string Options_Language {
            get {
                return ResourceManager.GetString("Options_Language", resourceCulture);
            }
        }

        internal static string Options_Language_SystemDefault {
            get {
                return ResourceManager.GetString("Options_Language_SystemDefault", resourceCulture);
            }
        }

        internal static string TrayMenu_About {
            get {
                return ResourceManager.GetString("TrayMenu_About", resourceCulture);
            }
        }

        internal static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }

        internal static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }

        internal static string About_Author {
            get {
                return ResourceManager.GetString("About_Author", resourceCulture);
            }
        }

        internal static string About_License {
            get {
                return ResourceManager.GetString("About_License", resourceCulture);
            }
        }

        internal static string License_Title {
            get {
                return ResourceManager.GetString("License_Title", resourceCulture);
            }
        }

        internal static string Options_CheckForUpdates {
            get {
                return ResourceManager.GetString("Options_CheckForUpdates", resourceCulture);
            }
        }

        internal static string Options_CheckNow {
            get {
                return ResourceManager.GetString("Options_CheckNow", resourceCulture);
            }
        }

        internal static string Options_CheckNow_NoUpdate {
            get {
                return ResourceManager.GetString("Options_CheckNow_NoUpdate", resourceCulture);
            }
        }

        internal static string Options_CheckNow_Failed {
            get {
                return ResourceManager.GetString("Options_CheckNow_Failed", resourceCulture);
            }
        }

        internal static string Update_Title {
            get {
                return ResourceManager.GetString("Update_Title", resourceCulture);
            }
        }

        internal static string Update_CurrentVersion {
            get {
                return ResourceManager.GetString("Update_CurrentVersion", resourceCulture);
            }
        }

        internal static string Update_NewVersion {
            get {
                return ResourceManager.GetString("Update_NewVersion", resourceCulture);
            }
        }

        internal static string Update_ReleaseNotes {
            get {
                return ResourceManager.GetString("Update_ReleaseNotes", resourceCulture);
            }
        }

        internal static string Update_BtnUpdateNow {
            get {
                return ResourceManager.GetString("Update_BtnUpdateNow", resourceCulture);
            }
        }

        internal static string Update_BtnRemindLater {
            get {
                return ResourceManager.GetString("Update_BtnRemindLater", resourceCulture);
            }
        }

        internal static string Update_BtnSkip {
            get {
                return ResourceManager.GetString("Update_BtnSkip", resourceCulture);
            }
        }

        internal static string Update_BalloonTitle {
            get {
                return ResourceManager.GetString("Update_BalloonTitle", resourceCulture);
            }
        }

        internal static string Update_BalloonText {
            get {
                return ResourceManager.GetString("Update_BalloonText", resourceCulture);
            }
        }

        internal static string Update_DownloadFailed {
            get {
                return ResourceManager.GetString("Update_DownloadFailed", resourceCulture);
            }
        }
    }
}
