//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTRegistryTree.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CTRegistryTree.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string Menu_Manage {
            get {
                return ResourceManager.GetString("Menu_Manage", resourceCulture);
            }
        }

        internal static string Tree_Root {
            get {
                return ResourceManager.GetString("Tree_Root", resourceCulture);
            }
        }

        internal static string Form_ManageItems_Title {
            get {
                return ResourceManager.GetString("Form_ManageItems_Title", resourceCulture);
            }
        }

        internal static string Button_Add {
            get {
                return ResourceManager.GetString("Button_Add", resourceCulture);
            }
        }

        internal static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }

        internal static string Button_Remove {
            get {
                return ResourceManager.GetString("Button_Remove", resourceCulture);
            }
        }

        internal static string Form_ManageItem_Title {
            get {
                return ResourceManager.GetString("Form_ManageItem_Title", resourceCulture);
            }
        }

        internal static string Label_Text {
            get {
                return ResourceManager.GetString("Label_Text", resourceCulture);
            }
        }

        internal static string Label_Action {
            get {
                return ResourceManager.GetString("Label_Action", resourceCulture);
            }
        }

        internal static string Label_Command {
            get {
                return ResourceManager.GetString("Label_Command", resourceCulture);
            }
        }

        internal static string Button_Find {
            get {
                return ResourceManager.GetString("Button_Find", resourceCulture);
            }
        }

        internal static string Button_Test {
            get {
                return ResourceManager.GetString("Button_Test", resourceCulture);
            }
        }

        internal static string ActionType_RunCommand {
            get {
                return ResourceManager.GetString("ActionType_RunCommand", resourceCulture);
            }
        }

        internal static string ActionType_OpenUrl {
            get {
                return ResourceManager.GetString("ActionType_OpenUrl", resourceCulture);
            }
        }

        internal static string ActionType_OpenFile {
            get {
                return ResourceManager.GetString("ActionType_OpenFile", resourceCulture);
            }
        }

        internal static string Button_Import {
            get {
                return ResourceManager.GetString("Button_Import", resourceCulture);
            }
        }

        internal static string Button_Export {
            get {
                return ResourceManager.GetString("Button_Export", resourceCulture);
            }
        }

        internal static string Dialog_XmlFilter {
            get {
                return ResourceManager.GetString("Dialog_XmlFilter", resourceCulture);
            }
        }

        internal static string Error_ImportFailed {
            get {
                return ResourceManager.GetString("Error_ImportFailed", resourceCulture);
            }
        }

        internal static string Error_ExportFailed {
            get {
                return ResourceManager.GetString("Error_ExportFailed", resourceCulture);
            }
        }
    }
}
